# This rule is not used by the project auto-inspection-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the devops.rxg98.cn.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: auto-inspection-operator
    app.kubernetes.io/managed-by: kustomize
  name: autoinspection-editor-role
rules:
- apiGroups:
  - devops.rxg98.cn
  resources:
  - autoinspections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.rxg98.cn
  resources:
  - autoinspections/status
  verbs:
  - get
