---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - devops.rxg98.cn
    resources:
      - autoinspections
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - devops.rxg98.cn
    resources:
      - autoinspections/finalizers
    verbs:
      - update
  - apiGroups:
      - devops.rxg98.cn
    resources:
      - autoinspections/status
    verbs:
      - get
      - patch
      - update
